config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show] do
    member do
      get 'orders'
    end
  end
  post "users/:id/authorize_user" => "users#authorize_user", as: "authorize_user"

  get 'admin/dashboard'
  get 'admin/users'
  get 'admin/sales'
  get 'admin/blog'
  get 'admin/products'
  get 'admin/orders/:id', to: 'admin#order_detail', as: 'admin_order'
  patch 'admin/orders/:id/mark_shipped', to: 'admin#mark_order_shipped', as: 'mark_order_shipped'

  resources :products
  resources :product_categories
  resources :variants
  resources :components
  
  resources :orders
  resources :order_items
  post "orders/:id/mark_order_paid" => "orders#mark_order_paid", as: "mark_order_paid"

  resources :bike_models
  resources :variant_models

  resources :blogs
  resources :blog_categories

  resources :photos
  post "photos/:id/approve_photo" => "photos#approve_photo", as: "approve_photo"



  namespace :api do
    namespace :v1 do
      post 'notify_admin', to: 'admin_notifications#create'
      resources :products do
        member do
          delete :remove_photo
        end
      end
      resources :components
      resources :variants do
        collection do
          get 'images'
        end
        member do
          delete :remove_photo
        end
      end
      resources :product_categories, only: [:index]
      resources :bike_models, only: [:index]
      resources :order_items
      resources :orders do
        member do
          post 'calculate_shipping_rates'
          get 'shipping_rates'
        end
      end
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :product_orders
  has_many :products, through: :order_items
  has_many :order_items
 
  def calculate_total_price
    total = order_items.sum(&:total_price)
    update(price: total)
    total
  end

  def total_price
    price || calculate_total_price
  end

  def shipping_info_complete?
    ship_to_name.present? &&
    customer_email.present? &&
    address_line_1.present? &&
    city.present? &&
    state.present? &&
    postal_code.present? &&
    country.present?
  end
  
  def order_number_of_items
    order_number_of_items = 0
    self.order_items.each do |item|
      order_number_of_items += item.quantity
    end
    order_number_of_items
  end

  def order_total
    order_total = 0
    self.order_items.each do |item|
      product = Product.find(item.product_id)
      order_total += ( product.price * item.quantity )
    end
    order_total
  end

  def price
    order_items.sum(&:total_price)
  end


end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
	before_action :set_current_order
	before_action :set_order, only: [:show, :update, :shipping_rates]

	require 'shippo'
  

	def index
		base_scope = Order.where(paypal_payment_status: "COMPLETED")

		if params[:search].present?
			term = "%#{params[:search]}%"
			base_scope = base_scope.where(
				"ship_to_name ILIKE :t OR customer_email ILIKE :t OR paypal_order_id ILIKE :t OR paypal_transaction_id ILIKE :t OR shipping_method_name ILIKE :t OR CAST(id AS TEXT) LIKE :t",
				t: term
			)
		end

		stats = {
			total_order_count: base_scope.count,
			total_revenue: base_scope.sum(:final_price).to_f.round(2),
			completed_count: base_scope.where(paypal_payment_status: "COMPLETED").count
		}

		page = [params.fetch(:page, 1).to_i, 1].max
		per_page = [params.fetch(:per_page, 20).to_i, 100].min
		total_count = stats[:total_order_count]
		total_pages = (total_count / per_page.to_f).ceil

		@orders = base_scope.order(created_at: :desc)
			.offset((page - 1) * per_page)
			.limit(per_page)

		render json: {
			orders: @orders,
			meta: { page: page, per_page: per_page, total_count: total_count, total_pages: total_pages },
			stats: stats
		}
	end

	def show
		@order = Order.find(params[:id])
		serialized_order = OrderSerializer.new(@order).as_json
		Rails.logger.debug "Serialized Order: #{serialized_order.inspect}"
		render json: serialized_order
	end

  
	def update
		paypal_payment_amount = params[:order].delete(:paypal_payment_amount)
		paypal_payment_currency = params[:order].delete(:paypal_payment_currency)
	  
		if @order.update(order_params)
		  if paypal_payment_amount.present?
			@order.update(final_price: paypal_payment_amount)
		  end
		  
		  # Associate order with current user if logged in
		  if current_user && @order.user_id.nil?
			@order.update(user_id: current_user.id)
		  end
	  
		  if @order.paypal_payment_status == 'COMPLETED'
			@order.update(paid_at: Time.current)
			
			puts "Resetting the order"
			new_order = Order.create!
			session[:order_id] = new_order.id
			@current_order = new_order
		  end
	  
		  render json: @order, include: ['order_items', 'order_items.product']
		else
		  render json: { errors: @order.errors }, status: :unprocessable_entity
		end
	end



	def calculate_shipping_rates
	  @order = Order.find(params[:id])
	  fetch_shipping_rates
	end
  

	def shipping_rates
	  Rails.logger.info "Shipping rates requested for order #{params[:id]}"
	  @order = Order.find(params[:id])
	  fetch_shipping_rates
	end
  

	def fetch_shipping_rates
	  @order = Order.find(params[:id])
	
	  unless @order.shipping_info_complete?
		render json: { error: "Shipping information is incomplete" }, status: :unprocessable_entity
		return
	  end
	
	  Shippo::API.token = ENV["SHIPPO_API_TOKEN"]
	
	  shippo_params = {
		async: false,
		address_from: {
		  name: 'Aloop Offroad',
		  company: 'Aloop Offroad',
		  street1: 'PO Box 412',
		  street2: '',
		  city: 'Sedalia',
		  state: 'CO',
		  zip: '80135',
		  country: 'US',
		  phone: '+1 303 550 2582'
		},
		address_to: {
		  name: @order.ship_to_name,
		  street1: @order.address_line_1,
		  street2: @order.address_line_2,
		  city: @order.city,
		  state: @order.state,
		  zip: @order.postal_code,
		  country: @order.country,
		  email: @order.customer_email
		},
		parcels: {
		  length: 5,
		  width: 2,
		  height: 5,
		  distance_unit: :in,
		  weight: 2,
		  mass_unit: :lb
		}
	  }
  
	  begin
		shipment = Shippo::Shipment.create(shippo_params)
		
		# Manually serialize the rates
		serialized_rates = shipment.rates.map do |rate|
		  {
			id: rate.object_id,
			amount: rate.amount,
			currency: rate.currency,
			provider: rate.provider,
			service_level: rate.servicelevel.name,
			estimated_days: rate.estimated_days,
			duration_terms: rate.duration_terms
		  }
		end
		
		render json: serialized_rates
	  rescue Shippo::Exceptions::APIServerError => e
		Rails.logger.error "Shippo API Error: #{e.message}"
		render json: { error: "Error calculating shipping rates" }, status: :service_unavailable
	  rescue => e
		Rails.logger.error "Unexpected error in Shippo API call: #{e.message}"
		render json: { error: "An unexpected error occurred" }, status: :internal_server_error
	  end
	end

  
	private

	def set_order
		@order = Order.find(params[:id])
	end

	def order_params
		params.require(:order).permit(
		  :paid, :token, :price, :move_to_checkout, :shipping_info,
		  :address_line_1, :address_line_2, :city, :state, :postal_code, :country,
		  :ship_to_name, :shipping_chosen, :shipping_choice, :shipping_choice_img, :shipping_method_name,
		  :shipping_cost, :customer_email, :final_price,
		  :paypal_order_id, :paypal_payer_id, :paypal_payer_email,
		  :paypal_payment_status, :paypal_transaction_id, :order_status,
		  :paid_at
		)
	end



  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ update destroy ]
  require 'shippo'

  def index
    @orders = Order.all
  end

  def show
    if Order.find_by(id: params[:id])
      @order = Order.find(params[:id])
    else
      @order = @current_order 
    end

    # Only create Shippo shipment if we're at the shipping step
    create_shippo_shipment if params[:step] == 'shipping'
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order) }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def mark_order_paid
    @order = Order.find(params[:id])
    if @order.update(paid: true, order_status: 'paid')
      @current_order = Order.create!
      session[:order_id] = @current_order.id

      redirect_to order_path(@order)
    else
      redirect_to order_path(@order)
      flash[:warning] = "Oops! Something went wrong!"
    end
  end

  private

  def create_shippo_shipment
    Shippo::API.token = ENV["SHIPPO_API_TOKEN"]

    params = {
      async: false,
      address_from: {
        name: 'Aloop Offroad',
        company: 'Aloop Offroad',
        street1: 'PO Box 412',
        street2: '',
        city: 'Sedalia',
        state: 'CO',
        zip: '80135',
        country: 'US',
        phone: '+1 303 550 2582'
      },
      address_to: {
        name: @order.ship_to_name,
        street1: @order.address_line_1,
        street2: @order.address_line_2,
        city: @order.city,
        state: @order.state,
        zip: @order.postal_code,
        country: @order.country,
        email: @order.customer_email
      },
      parcels: {
        length: 5,
        width: 2,
        height: 5,
        distance_unit: :in,
        weight: 2,
        mass_unit: :lb
      }
    }

    begin
      @shipment = Shippo::Shipment.create(params)
    rescue Shippo::Exceptions::APIServerError => e
      Rails.logger.error "Shippo API Error: #{e.message}"
      Rails.logger.error "Response: #{e.response.body}" if e.response
      @shipment = nil
      flash[:error] = "There was an error calculating shipping rates. Please try again later."
    rescue => e
      Rails.logger.error "Unexpected error in Shippo API call: #{e.message}"
      @shipment = nil
      flash[:error] = "An unexpected error occurred. Please try again later."
    end
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :id,
      :user_id,
      :price,
      :token,
      :move_to_checkout,
      :paid,
      :shipping_info,
      :ship_to_name,
      :customer_email,
      :address_line_1,
      :address_line_2,
      :city,
      :state,
      :postal_code,
      :country,
      :shipping_chosen,
      :shipping_choice,
      :shipping_method_name,
      :shipping_choice_img,
      :shipping_cost,
      :final_price,
      :paypal_order_id,
      :paypal_payer_id,
      :paypal_payer_email,
      :paypal_payment_status,
      :paypal_transaction_id,
      :order_status
    )
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :paid %>
    <%= f.input :token %>
    <%= f.input :price %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_form_paid.html.erb
<%#= simple_form_for(@order, html: { id: "formPaid" }) do |f| %>
    <%#= f.hidden_field :paid, value: true %>
<%# end %>

<%= link_to " ", mark_order_paid_path(@order), method: :post, id: "buttonPaid" %>

app/views/orders/_order_info.html.erb
<div class="w-75 ms-auto me-auto">
  <div class="row justify-content-center mb-2 box" >
    <div class="col-sm-6 col-md-4">
      <h4 class="uppercase">Order Info</h4>

      <table>
        <% @order.order_items.each do |item| %>
          <tr>
            <td><%= item.product.name %></td>
            <td><%= item.product.price %></td>
          </tr>
        <% end %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= item.product.price %></td>
        </tr>
      </table>
      <p>
        <ul class="mb-1">
          <% @order.order_items.each do |item| %>
            <li><%= item.product.name %></li>
          <% end %>
            <li>Shipping
        </ul>
        <strong>Order Total: <%= number_to_currency(@order.order_total) %></strong>
      </p>
    </div>
    <div class="col-sm-6 col-md-4">
      <h4 class="uppercase">Shipping Info</h4>
      <p class="mb-1">
        <%= @order.ship_to_name %>
        <br><%= @order.address_line_1 %>
        <% if @order.address_line_2 && @order.address_line_2 != "" %>
          <br><%= @order.address_line_2 %>
        <% end %>
        <br><%= @order.city %>, <%= @order.state %>  <%= @order.postal_code %>
        <br><%= @order.country %>
      </p>
      <% if edit_shipping_possible %>
        <%= simple_form_for(@order, html: { id: "formMoveToCheckout" }) do |f| %>
          <%= f.hidden_field :shipping_info, value: false %>
          <%= f.submit "Edit My Shipping Info", class: "btn-invisible text-link", style: "margin: 0px; padding: 0px; font-size: 0.8em; color: #c0c0c0" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/_payment.html.erb
<div id="paypal-button-container"></div>


<!-- Replace "test" with your own sandbox Business account app client ID -->
<script src="https://www.paypal.com/sdk/js?client-id=ATJK2vV0aAd9g8iShFQ2LccUACGyFaKJ0fn0nj9skdi506uCQFDrMF5mAil5P7JSBGGaIDUQcbFQkULD&currency=USD"></script>

<!-- Set up a container element for the button -->
<div id="paypal-button-container"></div>

<script>
  paypal.Buttons({
    // Sets up the transaction when a payment button is clicked
    createOrder: (data, actions) => {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '<%= @order.order_total %>' // Can also reference a variable or function
          }
        }]
      });
    },
    // Finalize the transaction after payer approval
    onApprove: (data, actions) => {
      return actions.order.capture().then(function(orderData) {
        // Successful capture! For dev/demo purposes:
        // console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
        // const transaction = orderData.purchase_units[0].payments.captures[0];
        
        // alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);
        // When ready to go live, remove the alert and show a success message within this page. For example:
        // const element = document.getElementById('paypal-button-container');
        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
        // actions.redirect('thank_you.html');
        // document.getElementById('formPaid').submit();
        document.getElementById('buttonPaid').click();
      });
    }
  }).render('#paypal-button-container');
</script>

app/views/orders/_step_1_cart.html.erb
<main id="notPaid" class="py-5 container">
  <header class="text-center">

    <% if current_user && current_user.admin && @order != @current_order %>
      <h1>Ongoing Shopping Cart</h1>
    <% else %>
      <h1>Your Cart</h1>
    <% end %>

  </header>

  <% if @order.order_items.count == 0 %>
    <p class="text-center">Nothing here yet!  You should head to our <%= link_to "store", products_path %> and fix that...</p>
  <% else %>

    <section id="cart-details" class="text-left pt-4">
      <table class="table">
        <tbody>
          <% @order.order_items.each do |item| %>
            <% product = Product.find(item.product_id) %>
            <tr>
              <td>
                <h4><%= product.name %></h4>
                <p class="mb-0 pb-0"><%= item.specs.html_safe %></p>
                <p class="mb-0 pb-0"><em><%= item.notes %></em></p>
                <br>
                <small><em>
                  <%= link_to "Remove", order_item_path(item), method: :delete, style: "text-decoration: none", data: {confirm: "Are you sure you want to remove that product from your cart?"} %>
                </em></small>
              </td>
              <td>
                <%= item.quantity %>
              </td>
              <td><%= number_to_currency(item.total_price) %></td>
            </tr>
          <% end %>
          <tr style="border-bottom: solid thin white">
            <th></th>
            <th style="text-align: right;">Total</th>
            <th>
              <% total_quantity = 0 %>
              <% @order.order_items.each do |item| %>
                <% total_quantity += item.quantity %>
              <% end %>
              <%= total_quantity %>
            </th>
            <th>
              <% total_price = 0 %>
              <% @order.order_items.each do |item| %>
                <% total_price += ( item.total_price * item.quantity )%>
              <% end %>
              <%= number_to_currency(total_price) %>
            </th>
          </tr>
        </tbody>
      </table>
    </section>

    <section id="actions" class="text-center mt-5">
      <h4>Ready to checkout?</h4>
      <% if current_user %>

        <%= simple_form_for(@order, html: { id: "formMoveToCheckout" }) do |f| %>
          <%= f.hidden_field :move_to_checkout, value: true %>
          <%= f.submit "Checkout", class: "btn" %>
        <% end %>

      <% else %>
        <%= link_to "Checkout", new_user_registration_path(order_id: order.id), class: "btn" %>
      <% end %>
    </section>

  <% end %>

</main>

app/views/orders/_step_2_shipping.html.erb
<main id="notPaid" class="py-5 container">
  <header class="text-center">

    <div class="progress mb-4 w-75 ms-auto me-auto">
      <div class="progress-bar" role="progressbar" style="width: 40%;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">40%</div>
    </div>

    <% if current_user && current_user.admin && @order != @current_order %>
      <h1>Shipping Information</h1>
    <% else %>
      <h1>Your Shipping Info</h1>
    <% end %>
    
  </header>




  <section class="text-center pt-4">
    <%= simple_form_for(@order) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs row">
        <%= f.hidden_field :shipping_info, value: true %>
        
        <div class="col-12 col-md-6">
          <%= f.input :ship_to_name %>
        </div> <!-- col -->
        <div class="col-12 col-md-6">
          <%= f.input :customer_email %>
        </div> <!-- col -->
        <div class="col-12 col-md-6">
          <%= f.input :address_line_1 %>
        </div> <!-- col -->
        <div class="col-12 col-md-6">
          <%= f.input :address_line_2 %>
        </div> <!-- col -->
        <div class="col-12 col-md-4">
          <%= f.input :city %>
        </div> <!-- col -->
        <div class="col-12 col-md-2">
          <%= f.input :state %>
        </div> <!-- col -->
        <div class="col-12 col-md-3">
          <%= f.input :postal_code %>
        </div> <!-- col -->
        <div class="col-12 col-md-3">
          <%= f.input :country, class: "countrypicker" %>
        </div> <!-- col -->

      </div> <!-- row -->
    </section>




    <section class="proceed-to-checkout">
      <div class="form-actions mt-5 text-center">
        <%= f.submit "See Shipping Options", class: "btn" %>
      </div>
    <% end %>
  </section>
  
</main>

app/views/orders/_step_3_shipping_options.html.erb
<main id="notPaid" class="py-5 container">

  <header class="text-center">

    <div class="progress mb-4 w-75 ms-auto me-auto">
      <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>
    </div>

    <% if current_user && current_user.admin && @order != @current_order %>
      <h1>Shipping Information</h1>
    <% else %>
      <h1>Shipping Options</h1>
    <% end %>
  </header>



  <section id="shipping-options" class="row">
    <% @shipment.rates.each do |rate| %>
      <div class="col-sm-6 col-xl-4 g-4">
        <div id="rate<%= rate.object_id %>" class="raised-box hoverable p-3 h-100">
          <div class="row align-items-top">
            <div class="col-2">
              <img src="<%= rate.provider_image_75 %>">
            </div> <!-- inner col -->
            <div class="col-10">
              <p class="h4 ms-2 mb-0 pb-0">
                 <%= number_to_currency(rate.amount) %>
              </p>
              <p class="ms-2 mb-0 pb-0" style="line-height: 1.1">
                <strong><%= rate.provider %>, <%= rate.servicelevel.name %></strong>
                <br><em><%= rate.duration_terms %></em>
              </p>
            </div> <!-- inner col -->            
          </div>
        </div>
      </div>
    <% end %>
  </section>



  <section class="proceed-to-checkout">
    <%= simple_form_for(@order) do |f| %>

      <%= f.hidden_field :shipping_chosen, id: "shipping-chosen" %>
      <%= f.hidden_field :shipping_choice, id: "shipping-choice" %>
      <%= f.hidden_field :shipping_choice_img, id: "shipping-img" %>
      <%= f.hidden_field :shipping_price, id: "shipping-price" %>
      <%= f.hidden_field :final_price, id: "price" %>

      <div class="form-actions mt-5 text-center">
        <%= f.submit "Proceed to Checkout", class: "btn" %>
      </div>
    <% end %>
  </section>

</main>







 <script>
  $( document ).ready(function() {
    <% @shipment.rates.each do |rate| %>
      $('#rate<%= rate.object_id %>').click(function() {
        $('.raised-box').removeClass('active');
        $(this).addClass('active');
        $('#shipping-chosen').val(true);
        $('#shipping-choice').val('<%= rate.provider %>');
        $('#shipping-img').val('<%= rate.provider_image_75 %>');
        $('#shipping-price').val(<%= rate.amount %>);
        $('#price').val('<%= @order.price + rate.amount.to_d %>');
      });
    <% end %>
  });
</script>

app/views/orders/_step_4_payment.html.erb
<main id="notPaid" class="py-5 container">
  <header class="text-center">
    <div class="progress mb-4 w-75 ms-auto me-auto">
      <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">80%</div>
    </div>

    <% if current_user && current_user.admin && @order != @current_order %>
      <h1>Payment To Be Made</h1>
    <% else %>
      <h1>Complete Your Payment</h1>
    <% end %>

    <p>Order #<%= order.id.to_s.rjust(6, "0") %></p>

  </header>

  <section>
    <%= render partial: "orders/order_info", locals: { edit_shipping_possible: true } %>
  </section>

  <section class="payment-boxes text-center pt-4">
    <%= render partial: "orders/payment", locals: { order: order } %>
    <%= render partial: "orders/form_paid", locals: { order: order } %>
  </section>
</main>

app/views/orders/_step_5_confirmation.html.erb
<main class="py-5 container">
  <header class="text-center">

    <div class="progress mb-4 w-75 ms-auto me-auto">
      <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">100%</div>
    </div>

    <% if current_user && current_user.admin && @order != @current_order %>
      <h1>Order Completed</h1>
    <% else %>
      <h1>Thank you for your order!</h1>
    <% end %>

    <p>Order #<%= order.id.to_s.rjust(6, "0") %></p>

  </header>

  <section class="my-5">
    <%= render partial: "orders/order_info", locals: { edit_shipping_possible: false } %>
  </section>
</main>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<% if current_user && current_user.admin && @current_order.id != @order.id %>
  <div class="container text-center mt-5">
    <div class="box w-75 ms-auto me-auto">
      <p class="uppercase mb-2">Admin Information</p>
      <% if @order.move_to_checkout == false %><div class="badge mx-1">Cart Created</div><% end %>
      <% if @order.move_to_checkout == true %><div class="badge mx-1">Moved to Checkout</div><% end %>
      <% if @order.shipping_info == true %><div class="badge mx-1">Shipping Info Entered</div><% end %>
      <% if @order.paid == true %><div class="badge mx-1">Paid</div><% end %>
      <% if @order.move_to_checkout == true %><div class="badge mx-1">Moved to Checkout</div><% end %>
    </div>
  </div>
<% end %>


<% if @order.move_to_checkout == false && @order.shipping_info == false && @order.paid == false %>
  <%= render partial: "orders/step_1_cart", locals: { order: @order } %>
<% elsif @order.shipping_info == false && @order.paid == false %>
  <%= render partial: "orders/step_2_shipping", locals: { order: @order } %>
<% elsif @order.shipping_info == true && @order.shipping_chosen == false %>
  <%= render partial: "orders/step_3_shipping_options", locals: { order: @order } %>
<% elsif @order.paid == false %>
  <%= render partial: "orders/step_4_payment", locals: { order: @order } %>
<% elsif @order.paid %>
  <%= render partial: "orders/step_5_confirmation", locals: { order: @order } %>
<% end %>