config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show] do
    member do
      get 'orders'
    end
  end
  post "users/:id/authorize_user" => "users#authorize_user", as: "authorize_user"

  get 'admin/dashboard'
  get 'admin/users'
  get 'admin/sales'
  get 'admin/blog'
  get 'admin/products'
  get 'admin/orders/:id', to: 'admin#order_detail', as: 'admin_order'
  patch 'admin/orders/:id/mark_shipped', to: 'admin#mark_order_shipped', as: 'mark_order_shipped'

  resources :products
  resources :product_categories
  resources :variants
  resources :components
  
  resources :orders
  resources :order_items
  post "orders/:id/mark_order_paid" => "orders#mark_order_paid", as: "mark_order_paid"

  resources :bike_models
  resources :variant_models

  resources :blogs
  resources :blog_categories

  resources :photos
  post "photos/:id/approve_photo" => "photos#approve_photo", as: "approve_photo"



  namespace :api do
    namespace :v1 do
      post 'notify_admin', to: 'admin_notifications#create'
      resources :products do
        member do
          delete :remove_photo
        end
      end
      resources :components
      resources :variants do
        collection do
          get 'images'
        end
        member do
          delete :remove_photo
        end
      end
      resources :product_categories, only: [:index]
      resources :bike_models, only: [:index]
      resources :order_items
      resources :orders do
        member do
          post 'calculate_shipping_rates'
          get 'shipping_rates'
        end
      end
    end
  end


end

app/views/layouts/_footer.html.erb
<footer class="w-100 py-4 flex-shrink-0 bg-grey">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-12 col-sm-2 text-center">
                    <img class="w-100" src="https://aloopphotobucket.s3.us-west-1.amazonaws.com/Images/Logo/Logo.png" />
                </div>
                <div class="col-12 col-sm-10">
                    <h5 class="color-red mb-3 thin">Contact Aloop</h5>
                    <p class="small mb-2">
                    	Our office hours vary greatly by season and workload, but your business is very important to us. You can contact us by text message at 303-550-2582, or by email at sales@aloop.com. We try to respond to all inquiries within 24 hours or less.
					</p>
					<p class="small mb-3">
						We are located in the USA Mountain Time Zone (GMT-7hrs).
                    </p>

                    <h5 class="color-red mb-3 thin">Overseas Orders</h5>
                    <p class="small mb-2">
                    	Overseas orders are no problem!
					</p>
					<p class="small mb-3">
						We've sold thousands of our Aloop 4SMX kits to customers in over 40 countries! Most shipments are sent via US Mail Global Express Mail, and can arrive in under 1 week, no matter where in the world you live.
                    </p>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md px-3 navbar-light bg-white">
  <div class="container-fluid">

    <div id="slide">
    <%= link_to root_path, class: "navbar-brand" do %>
      <img style="height: 35px; margin-right: 0px" src="https://aloopphotobucket.s3.us-west-1.amazonaws.com/Images/Logo/Logo+(Symbol).png" />
      <img style="height: 40px" src="https://aloopphotobucket.s3.us-west-1.amazonaws.com/Images/Logo/Logo+(Text).png" />
    <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">

        <li class="nav-item dropdown">
          <%= link_to "Kits", page_path("kits"), class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink", 'data-toggle': "dropdown", 'aria-haspopup': "true", 'aria-expanded': "false" %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "XR250 and XR400", page_path("XR250_XR400"), class: "dropdown-item" %>
            <%= link_to "XR600", page_path("XR600"), class: "dropdown-item" %>
            <%= link_to "XR650L", page_path("XR650L"), class: "dropdown-item" %>
            <%= link_to "Graphics", page_path("graphics"), class: "dropdown-item" %>
            <%= link_to "Color Coded Key Covers", products_path, class: "dropdown-item" %>
            <%= link_to "Rear Fenders", products_path, class: "dropdown-item" %>
            <%= link_to "Replacement Parts", products_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item"><%= link_to "Gallery", photos_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Store", products_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "FAQ", page_path("faq"), class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Export", page_path("export"), class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Blog", blogs_path, class: "nav-link" %></li>

        <% if current_user && current_user.admin %>
          <li class="nav-item dropdown">
            <%= link_to "Admin", admin_dashboard_path, class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink", 'data-toggle': "dropdown", 'aria-haspopup': "true", 'aria-expanded': "false" %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Products", admin_products_path, class: "dropdown-item" %>
              <%= link_to "Sales", admin_sales_path, class: "dropdown-item" %>
              <%= link_to "Users", admin_users_path, class: "dropdown-item" %>
              <%= link_to "Blog", admin_blog_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "My Account", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Order History", orders_user_path(current_user), class: "dropdown-item" %>
              <%= button_to "Sign Out", destroy_user_session_path, :method => :delete, class: "dropdown-item", style: "text-transform: uppercase" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Create an Account", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

        <li>
          <%= link_to page_path("cart"), class: "position-relative w-0" do %>
            <i class='fas fa-shopping-cart'></i>            
            <% if @current_order.order_number_of_items != 0 %>
              <span class="position-absolute translate-middle badge rounded-pill bg-danger">
                <%= @current_order.order_number_of_items %>
              </span>
            <% end %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<!-- flash notice area -->
<div class="flash-notice-area">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:warning] %>
    <div class="alert alert-warning">
      <%= flash[:warning] %>
    </div>
  <% end %>
</div>
<!-- flash notice area -->

app/views/layouts/_ways_to_order.html.erb
<section class="py-5 bg-gears">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-10 col-xl-7">
                <div class="text-center">
                    <div class="raised-box p-4">

                        <div class="row text-center">
                            <h2 class="thin">There Are 3 Ways to Order from Aloop</h2>
                            <div class="col-sm-4">
                                <i class="fas fa-shopping-cart display-1 my-3 color-red"></i>
                                <h3 class="color-blue thin">Order Online</h3>
                                <p>You can order any of our products on our online store.</p>
                            </div> <!-- col -->
                            <div class="col-sm-4">
                                <i class="fas fa-at display-1 my-3 color-red"></i>
                                <h3 class="color-blue thin">Send an Email</h3>
                                <p>We welcome orders, reviews, and questions by email.</p>
                            </div> <!-- col -->
                            <div class="col-sm-4">
                                <i class="fas fa-envelope display-1 my-3 color-red"></i>
                                <h3 class="color-blue thin">Postal Service</h3>
                                <p>You can post orders as well as any questions you might have.</p>
                            </div> <!-- col -->                            
                        </div> <!-- row -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Aloop Offroad</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <% if user_signed_in? %>
      <meta name="user-signed-in" content="true">
      <meta name="current-user-id" content="<%= current_user.id %>">
    <% else %>
      <meta name="user-signed-in" content="false">
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application", defer: true %>

    <!-- FAVICONS -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <% unless Rails.env.test? %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.1.2/tinymce.min.js" integrity="sha512-cJ2vUNryvHzgNJfmFTtZ2VX5EMT5JOU1i8nm+L1kwoHQ9bSqSYdswxyk++9Gi27p3BG2rXZXLMsTsluY4RZSSw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <% end %>

    <%= javascript_tag do %>
      window.TINY_MCE_API_KEY = '<%= ENV['TINY_MCE_API_KEY'] %>';
      window.PAYPAL_CLIENT_ID = '<%= ENV['PAYPAL_CLIENT_ID'] %>';
    <% end %>
  </head>

  <body>
    <div class="non-footer">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/notifications' %>
      <%= render 'layouts/sidenav' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  
    <%= yield :additional_js %>
  </body>
</html>